'use client';

import { useState, useTransition } from 'react';
import { motion } from 'framer-motion';
import { toast } from 'sonner';
import {
  Calendar,
  Clock,
  ListChecks,
  MapPin,
  StickyNote,
  Wrench,
  X,
  Youtube,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input, Label } from '@/components/ui/input';
import {
  upsertTaskFromPlanAction,
  scheduleTaskAction,
  type UpsertTaskInput,
} from '@/server/actions/maintenance-tasks';
import type {
  MaintenanceCategory,
  MaintenanceTaskInstructions,
} from '@/lib/types';
import { getInstructions } from '@/lib/maintenance/instructions';

interface IncomingTask {
  /** ID of the persisted task. If null, the task is still in-memory only
   * (generated by the plan engine) and we need to upsert it first. */
  id?: string | null;
  vehicleId: string;
  category: MaintenanceCategory;
  title: string;
  description?: string | null;
  reasoning?: string | null;
  confidence?: number | null;
  estimatedCost?: number | null;
  dueAtDate?: string | null;
  dueAtKm?: number | null;
  source?: 'plan' | 'phm' | 'manual';
}

interface Props {
  task: IncomingTask;
  open: boolean;
  onClose: () => void;
  onScheduled?: () => void;
}

export function ScheduleTaskModal({ task, open, onClose, onScheduled }: Props) {
  const [pending, startTransition] = useTransition();
  const defaultDate = (task.dueAtDate ?? new Date().toISOString()).slice(0, 10);
  const [scheduledFor, setScheduledFor] = useState(defaultDate);
  const [reminderDays, setReminderDays] = useState('7');
  const [garageName, setGarageName] = useState('');
  const [notes, setNotes] = useState('');

  const instructions: MaintenanceTaskInstructions = getInstructions(task.category);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    startTransition(async () => {
      let taskId = task.id ?? null;

      // First upsert the IA prediction so we have a real row to schedule.
      if (!taskId) {
        const upsertInput: UpsertTaskInput = {
          vehicleId: task.vehicleId,
          category: task.category,
          title: task.title,
          description: task.description ?? null,
          reasoning: task.reasoning ?? null,
          confidence: task.confidence ?? null,
          estimatedCost: task.estimatedCost ?? null,
          dueAtDate: task.dueAtDate ?? null,
          dueAtKm: task.dueAtKm ?? null,
          source: task.source ?? 'plan',
        };
        const up = await upsertTaskFromPlanAction(upsertInput);
        if (up.error) {
          toast.error(up.error);
          return;
        }
        taskId = up.id ?? null;
      }
      if (!taskId) {
        toast.error('Impossible de créer la tâche.');
        return;
      }

      const sched = await scheduleTaskAction({
        taskId,
        scheduledFor,
        reminderDaysBefore: Number(reminderDays || 7),
        garageName: garageName.trim() || null,
        notes: notes.trim() || null,
      });
      if (sched.error) {
        toast.error(sched.error);
        return;
      }
      toast.success('Tâche planifiée. Un rappel vous sera envoyé.');
      onScheduled?.();
      onClose();
    });
  };

  if (!open) return null;

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.15 }}
      onClick={() => !pending && onClose()}
      className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4 overflow-y-auto"
    >
      <motion.div
        initial={{ opacity: 0, scale: 0.96, y: 12 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.96, y: 12 }}
        transition={{ duration: 0.18, ease: 'easeOut' }}
        onClick={(e) => e.stopPropagation()}
        className="w-full max-w-2xl my-8 rounded-card border border-border bg-card shadow-elevated overflow-hidden"
      >
        <div className="flex items-start justify-between border-b border-border p-5 gap-3">
          <div className="flex items-start gap-3 min-w-0">
            <div className="rounded-btn bg-veloce/10 text-veloce p-2 shrink-0">
              <Wrench className="h-5 w-5" strokeWidth={2} />
            </div>
            <div className="min-w-0">
              <h2 className="font-display text-base font-bold">{task.title}</h2>
              {task.description && (
                <p className="text-xs text-muted-foreground mt-0.5">
                  {task.description}
                </p>
              )}
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            disabled={pending}
            className="text-muted-foreground hover:text-foreground disabled:opacity-30 shrink-0"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-5 space-y-5">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div className="space-y-1 sm:col-span-2">
              <Label htmlFor="sched-date" className="text-xs flex items-center gap-1.5">
                <Calendar className="h-3.5 w-3.5" />
                Date prévue
              </Label>
              <Input
                id="sched-date"
                type="date"
                value={scheduledFor}
                min={new Date().toISOString().slice(0, 10)}
                onChange={(e) => setScheduledFor(e.target.value)}
                required
                className="font-mono"
              />
            </div>
            <div className="space-y-1">
              <Label htmlFor="sched-reminder" className="text-xs flex items-center gap-1.5">
                <Clock className="h-3.5 w-3.5" />
                Rappel
              </Label>
              <select
                id="sched-reminder"
                value={reminderDays}
                onChange={(e) => setReminderDays(e.target.value)}
                className="w-full rounded-btn border border-border bg-card px-3 py-1.5 text-sm h-10"
              >
                <option value="14">14 jours avant</option>
                <option value="7">7 jours avant</option>
                <option value="3">3 jours avant</option>
                <option value="1">1 jour avant</option>
                <option value="0">Aucun</option>
              </select>
            </div>
          </div>

          <div className="space-y-1">
            <Label htmlFor="sched-garage" className="text-xs flex items-center gap-1.5">
              <MapPin className="h-3.5 w-3.5" />
              Garage / lieu (optionnel)
            </Label>
            <Input
              id="sched-garage"
              value={garageName}
              onChange={(e) => setGarageName(e.target.value)}
              placeholder="Ex: Speedy Bercy"
              maxLength={120}
            />
          </div>

          <div className="space-y-1">
            <Label htmlFor="sched-notes" className="text-xs flex items-center gap-1.5">
              <StickyNote className="h-3.5 w-3.5" />
              Notes
            </Label>
            <textarea
              id="sched-notes"
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              rows={3}
              maxLength={2000}
              placeholder="Précisions, références à apporter, devis…"
              className="w-full rounded-card border border-border bg-card px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-ring resize-none"
            />
          </div>

          {/* Instructions block — read-only, helps the user plan */}
          <div className="rounded-card border border-border bg-muted/20 p-4 space-y-3">
            <div className="flex items-center justify-between gap-2">
              <h3 className="text-xs font-semibold uppercase tracking-wider flex items-center gap-1.5">
                <ListChecks className="h-3.5 w-3.5 text-veloce" />
                Checklist d'intervention
              </h3>
              <div className="text-[11px] text-muted-foreground font-mono">
                ~{instructions.durationMinutes} min · difficulté{' '}
                {instructions.diyDifficulty}/5
              </div>
            </div>
            <ul className="space-y-1.5 text-xs">
              {instructions.checklist.map((step, i) => (
                <li
                  key={i}
                  className="flex gap-2 items-start text-foreground/85"
                >
                  <span className="font-mono text-veloce text-[10px] shrink-0 mt-0.5">
                    {String(i + 1).padStart(2, '0')}
                  </span>
                  <span>{step}</span>
                </li>
              ))}
            </ul>
            {instructions.tools.length > 0 && (
              <div>
                <div className="text-[10px] uppercase tracking-wider text-muted-foreground mb-1">
                  Outils
                </div>
                <div className="flex flex-wrap gap-1.5">
                  {instructions.tools.map((tool) => (
                    <span
                      key={tool}
                      className="text-[10px] px-2 py-0.5 rounded-full border border-border bg-card text-muted-foreground"
                    >
                      {tool}
                    </span>
                  ))}
                </div>
              </div>
            )}
            {instructions.tutorialUrl && (
              <a
                href={instructions.tutorialUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="text-xs text-veloce hover:underline flex items-center gap-1 mt-1"
              >
                <Youtube className="h-3 w-3" />
                Voir le tutoriel détaillé
              </a>
            )}
          </div>

          {task.reasoning && (
            <p className="text-[11px] text-muted-foreground italic border-l-2 border-veloce/30 pl-3">
              {task.reasoning}
            </p>
          )}

          <div className="flex justify-end gap-2 pt-2">
            <Button
              type="button"
              variant="ghost"
              onClick={onClose}
              disabled={pending}
            >
              Annuler
            </Button>
            <Button
              type="submit"
              disabled={pending}
              className="bg-veloce hover:bg-veloce/90 text-white"
            >
              {pending ? 'Planification…' : 'Planifier et activer le rappel'}
            </Button>
          </div>
        </form>
      </motion.div>
    </motion.div>
  );
}
